version: '3.5'
services:
  database:
    image:  postgres:14
    container_name: database
    hostname: database
    volumes:
      - ./data/database:/var/lib/postgresql/data
    ports:
      - 5532:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    restart: always
