# Generated by Django 3.2.16 on 2023-04-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230427_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='login',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='login',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
