# Generated by Django 3.2.16 on 2023-04-27 16:08

import core.utils.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230427_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='schema_path',
        ),
        migrations.AddField(
            model_name='construction',
            name='schema_file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.util.get_schema_file_path),
        ),
        migrations.AlterField(
            model_name='construction',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
